/* Generated by using kysely-codegen on PostgreSQL 13, patching
   kysely postgresql/introspection.ts to also return the system tables.

   postgresql-client currently doesn't support the Interval type (from package 'postgres-interval'),
   so the Interval should be edited out manually until it is supported.

   Instructions:
   ```
   mkdir /tmp/codegen-tempdir
   cd /tmp/codegen-tempdir
   npm init -y
   npm install -y kysely-codegen kysely pg
   ```

   Edit the file `/tmp/codegen-tempdir/node_modules/kysely/dist/cjs/dialect/postgres/postgres-introspector.js`
   and comment out the following lines:
   ```
             .where('ns.nspname', '!~', '^pg_')
             .where('ns.nspname', '!=', 'information_schema')
   ```

   After that, run
   ```
   DATABASE_URL="postgres://postgres@webhare?host=$(wh getdatadir)/postgresql" node_modules/.bin/kysely-codegen
   ```

   then copy the contents from `/tmp/codegen-tempdir/node_modules/kysely-codegen/dist/db.d.ts` to this file.
   Remove the import from "postgres-interval", and refine Interval to be
   ```
   export type Interval = ColumnType<never, never, never>;
   ```
*/

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, string | number | bigint, string | number | bigint>;

export type Interval = ColumnType<never, never, never>;

export type Numeric = ColumnType<string, string | number, string | number>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface InformationSchemaAdministrableRoleAuthorizations {
  grantee: string | null;
  role_name: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaApplicableRoles {
  grantee: string | null;
  role_name: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaAttributes {
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  attribute_name: string | null;
  ordinal_position: string | null;
  attribute_default: string | null;
  is_nullable: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  attribute_udt_catalog: string | null;
  attribute_udt_schema: string | null;
  attribute_udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
  is_derived_reference_attribute: string | null;
}

export interface InformationSchemaCharacterSets {
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  character_repertoire: string | null;
  form_of_use: string | null;
  default_collate_catalog: string | null;
  default_collate_schema: string | null;
  default_collate_name: string | null;
}

export interface InformationSchemaCheckConstraintRoutineUsage {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
}

export interface InformationSchemaCheckConstraints {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  check_clause: string | null;
}

export interface InformationSchemaCollationCharacterSetApplicability {
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
}

export interface InformationSchemaCollations {
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  pad_attribute: string | null;
}

export interface InformationSchemaColumnColumnUsage {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  dependent_column: string | null;
}

export interface InformationSchemaColumnDomainUsage {
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
}

export interface InformationSchemaColumnOptions {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  option_name: string | null;
  option_value: string | null;
}

export interface InformationSchemaColumnPrivileges {
  grantor: string | null;
  grantee: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaColumns {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  ordinal_position: string | null;
  column_default: string | null;
  is_nullable: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
  is_self_referencing: string | null;
  is_identity: string | null;
  identity_generation: string | null;
  identity_start: string | null;
  identity_increment: string | null;
  identity_maximum: string | null;
  identity_minimum: string | null;
  identity_cycle: string | null;
  is_generated: string | null;
  generation_expression: string | null;
  is_updatable: string | null;
}

export interface InformationSchemaColumnUdtUsage {
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
}

export interface InformationSchemaConstraintColumnUsage {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
}

export interface InformationSchemaConstraintTableUsage {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
}

export interface InformationSchemaDataTypePrivileges {
  object_catalog: string | null;
  object_schema: string | null;
  object_name: string | null;
  object_type: string | null;
  dtd_identifier: string | null;
}

export interface InformationSchemaDomainConstraints {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
  is_deferrable: string | null;
  initially_deferred: string | null;
}

export interface InformationSchemaDomains {
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  domain_default: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
}

export interface InformationSchemaDomainUdtUsage {
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
}

export interface InformationSchemaElementTypes {
  object_catalog: string | null;
  object_schema: string | null;
  object_name: string | null;
  object_type: string | null;
  collection_type_identifier: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  domain_default: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
}

export interface InformationSchemaEnabledRoles {
  role_name: string | null;
}

export interface InformationSchemaForeignDataWrapperOptions {
  foreign_data_wrapper_catalog: string | null;
  foreign_data_wrapper_name: string | null;
  option_name: string | null;
  option_value: string | null;
}

export interface InformationSchemaForeignDataWrappers {
  foreign_data_wrapper_catalog: string | null;
  foreign_data_wrapper_name: string | null;
  authorization_identifier: string | null;
  library_name: string | null;
  foreign_data_wrapper_language: string | null;
}

export interface InformationSchemaForeignServerOptions {
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  option_name: string | null;
  option_value: string | null;
}

export interface InformationSchemaForeignServers {
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  foreign_data_wrapper_catalog: string | null;
  foreign_data_wrapper_name: string | null;
  foreign_server_type: string | null;
  foreign_server_version: string | null;
  authorization_identifier: string | null;
}

export interface InformationSchemaForeignTableOptions {
  foreign_table_catalog: string | null;
  foreign_table_schema: string | null;
  foreign_table_name: string | null;
  option_name: string | null;
  option_value: string | null;
}

export interface InformationSchemaForeignTables {
  foreign_table_catalog: string | null;
  foreign_table_schema: string | null;
  foreign_table_name: string | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
}

export interface InformationSchemaInformationSchemaCatalogName {
  catalog_name: string | null;
}

export interface InformationSchemaKeyColumnUsage {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  ordinal_position: string | null;
  position_in_unique_constraint: string | null;
}

export interface InformationSchemaParameters {
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
  ordinal_position: string | null;
  parameter_mode: string | null;
  is_result: string | null;
  as_locator: string | null;
  parameter_name: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
  parameter_default: string | null;
}

export interface InformationSchemaPgForeignDataWrappers {
  oid: number | null;
  fdwowner: number | null;
  fdwoptions: string[] | null;
  foreign_data_wrapper_catalog: string | null;
  foreign_data_wrapper_name: string | null;
  authorization_identifier: string | null;
  foreign_data_wrapper_language: string | null;
}

export interface InformationSchemaPgForeignServers {
  oid: number | null;
  srvoptions: string[] | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  foreign_data_wrapper_catalog: string | null;
  foreign_data_wrapper_name: string | null;
  foreign_server_type: string | null;
  foreign_server_version: string | null;
  authorization_identifier: string | null;
}

export interface InformationSchemaPgForeignTableColumns {
  nspname: string | null;
  relname: string | null;
  attname: string | null;
  attfdwoptions: string[] | null;
}

export interface InformationSchemaPgForeignTables {
  foreign_table_catalog: string | null;
  foreign_table_schema: string | null;
  foreign_table_name: string | null;
  ftoptions: string[] | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  authorization_identifier: string | null;
}

export interface InformationSchemaPgUserMappings {
  oid: number | null;
  umoptions: string[] | null;
  umuser: number | null;
  authorization_identifier: string | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  srvowner: string | null;
}

export interface InformationSchemaReferentialConstraints {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  unique_constraint_catalog: string | null;
  unique_constraint_schema: string | null;
  unique_constraint_name: string | null;
  match_option: string | null;
  update_rule: string | null;
  delete_rule: string | null;
}

export interface InformationSchemaRoleColumnGrants {
  grantor: string | null;
  grantee: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaRoleRoutineGrants {
  grantor: string | null;
  grantee: string | null;
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
  routine_catalog: string | null;
  routine_schema: string | null;
  routine_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaRoleTableGrants {
  grantor: string | null;
  grantee: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
  with_hierarchy: string | null;
}

export interface InformationSchemaRoleUdtGrants {
  grantor: string | null;
  grantee: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaRoleUsageGrants {
  grantor: string | null;
  grantee: string | null;
  object_catalog: string | null;
  object_schema: string | null;
  object_name: string | null;
  object_type: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaRoutinePrivileges {
  grantor: string | null;
  grantee: string | null;
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
  routine_catalog: string | null;
  routine_schema: string | null;
  routine_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaRoutines {
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
  routine_catalog: string | null;
  routine_schema: string | null;
  routine_name: string | null;
  routine_type: string | null;
  module_catalog: string | null;
  module_schema: string | null;
  module_name: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  type_udt_catalog: string | null;
  type_udt_schema: string | null;
  type_udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: string | null;
  dtd_identifier: string | null;
  routine_body: string | null;
  routine_definition: string | null;
  external_name: string | null;
  external_language: string | null;
  parameter_style: string | null;
  is_deterministic: string | null;
  sql_data_access: string | null;
  is_null_call: string | null;
  sql_path: string | null;
  schema_level_routine: string | null;
  max_dynamic_result_sets: string | null;
  is_user_defined_cast: string | null;
  is_implicitly_invocable: string | null;
  security_type: string | null;
  to_sql_specific_catalog: string | null;
  to_sql_specific_schema: string | null;
  to_sql_specific_name: string | null;
  as_locator: string | null;
  created: string | null;
  last_altered: string | null;
  new_savepoint_level: string | null;
  is_udt_dependent: string | null;
  result_cast_from_data_type: string | null;
  result_cast_as_locator: string | null;
  result_cast_char_max_length: string | null;
  result_cast_char_octet_length: string | null;
  result_cast_char_set_catalog: string | null;
  result_cast_char_set_schema: string | null;
  result_cast_char_set_name: string | null;
  result_cast_collation_catalog: string | null;
  result_cast_collation_schema: string | null;
  result_cast_collation_name: string | null;
  result_cast_numeric_precision: string | null;
  result_cast_numeric_precision_radix: string | null;
  result_cast_numeric_scale: string | null;
  result_cast_datetime_precision: string | null;
  result_cast_interval_type: string | null;
  result_cast_interval_precision: string | null;
  result_cast_type_udt_catalog: string | null;
  result_cast_type_udt_schema: string | null;
  result_cast_type_udt_name: string | null;
  result_cast_scope_catalog: string | null;
  result_cast_scope_schema: string | null;
  result_cast_scope_name: string | null;
  result_cast_maximum_cardinality: string | null;
  result_cast_dtd_identifier: string | null;
}

export interface InformationSchemaSchemata {
  catalog_name: string | null;
  schema_name: string | null;
  schema_owner: string | null;
  default_character_set_catalog: string | null;
  default_character_set_schema: string | null;
  default_character_set_name: string | null;
  sql_path: string | null;
}

export interface InformationSchemaSequences {
  sequence_catalog: string | null;
  sequence_schema: string | null;
  sequence_name: string | null;
  data_type: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  start_value: string | null;
  minimum_value: string | null;
  maximum_value: string | null;
  increment: string | null;
  cycle_option: string | null;
}

export interface InformationSchemaSqlFeatures {
  feature_id: string | null;
  feature_name: string | null;
  sub_feature_id: string | null;
  sub_feature_name: string | null;
  is_supported: string | null;
  is_verified_by: string | null;
  comments: string | null;
}

export interface InformationSchemaSqlImplementationInfo {
  implementation_info_id: string | null;
  implementation_info_name: string | null;
  integer_value: string | null;
  character_value: string | null;
  comments: string | null;
}

export interface InformationSchemaSqlParts {
  feature_id: string | null;
  feature_name: string | null;
  is_supported: string | null;
  is_verified_by: string | null;
  comments: string | null;
}

export interface InformationSchemaSqlSizing {
  sizing_id: string | null;
  sizing_name: string | null;
  supported_value: string | null;
  comments: string | null;
}

export interface InformationSchemaTableConstraints {
  constraint_catalog: string | null;
  constraint_schema: string | null;
  constraint_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  constraint_type: string | null;
  is_deferrable: string | null;
  initially_deferred: string | null;
  enforced: string | null;
}

export interface InformationSchemaTablePrivileges {
  grantor: string | null;
  grantee: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
  with_hierarchy: string | null;
}

export interface InformationSchemaTables {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  table_type: string | null;
  self_referencing_column_name: string | null;
  reference_generation: string | null;
  user_defined_type_catalog: string | null;
  user_defined_type_schema: string | null;
  user_defined_type_name: string | null;
  is_insertable_into: string | null;
  is_typed: string | null;
  commit_action: string | null;
}

export interface InformationSchemaTransforms {
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
  group_name: string | null;
  transform_type: string | null;
}

export interface InformationSchemaTriggeredUpdateColumns {
  trigger_catalog: string | null;
  trigger_schema: string | null;
  trigger_name: string | null;
  event_object_catalog: string | null;
  event_object_schema: string | null;
  event_object_table: string | null;
  event_object_column: string | null;
}

export interface InformationSchemaTriggers {
  trigger_catalog: string | null;
  trigger_schema: string | null;
  trigger_name: string | null;
  event_manipulation: string | null;
  event_object_catalog: string | null;
  event_object_schema: string | null;
  event_object_table: string | null;
  action_order: string | null;
  action_condition: string | null;
  action_statement: string | null;
  action_orientation: string | null;
  action_timing: string | null;
  action_reference_old_table: string | null;
  action_reference_new_table: string | null;
  action_reference_old_row: string | null;
  action_reference_new_row: string | null;
  created: string | null;
}

export interface InformationSchemaUdtPrivileges {
  grantor: string | null;
  grantee: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaUsagePrivileges {
  grantor: string | null;
  grantee: string | null;
  object_catalog: string | null;
  object_schema: string | null;
  object_name: string | null;
  object_type: string | null;
  privilege_type: string | null;
  is_grantable: string | null;
}

export interface InformationSchemaUserDefinedTypes {
  user_defined_type_catalog: string | null;
  user_defined_type_schema: string | null;
  user_defined_type_name: string | null;
  user_defined_type_category: string | null;
  is_instantiable: string | null;
  is_final: string | null;
  ordering_form: string | null;
  ordering_category: string | null;
  ordering_routine_catalog: string | null;
  ordering_routine_schema: string | null;
  ordering_routine_name: string | null;
  reference_type: string | null;
  data_type: string | null;
  character_maximum_length: string | null;
  character_octet_length: string | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  numeric_precision: string | null;
  numeric_precision_radix: string | null;
  numeric_scale: string | null;
  datetime_precision: string | null;
  interval_type: string | null;
  interval_precision: string | null;
  source_dtd_identifier: string | null;
  ref_dtd_identifier: string | null;
}

export interface InformationSchemaUserMappingOptions {
  authorization_identifier: string | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
  option_name: string | null;
  option_value: string | null;
}

export interface InformationSchemaUserMappings {
  authorization_identifier: string | null;
  foreign_server_catalog: string | null;
  foreign_server_name: string | null;
}

export interface InformationSchemaViewColumnUsage {
  view_catalog: string | null;
  view_schema: string | null;
  view_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  column_name: string | null;
}

export interface InformationSchemaViewRoutineUsage {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  specific_catalog: string | null;
  specific_schema: string | null;
  specific_name: string | null;
}

export interface InformationSchemaViews {
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
  view_definition: string | null;
  check_option: string | null;
  is_updatable: string | null;
  is_insertable_into: string | null;
  is_trigger_updatable: string | null;
  is_trigger_deletable: string | null;
  is_trigger_insertable_into: string | null;
}

export interface InformationSchemaViewTableUsage {
  view_catalog: string | null;
  view_schema: string | null;
  view_name: string | null;
  table_catalog: string | null;
  table_schema: string | null;
  table_name: string | null;
}

export interface PgCatalogPgAggregate {
  aggfnoid: string;
  aggkind: string;
  aggnumdirectargs: number;
  aggtransfn: string;
  aggfinalfn: string;
  aggcombinefn: string;
  aggserialfn: string;
  aggdeserialfn: string;
  aggmtransfn: string;
  aggminvtransfn: string;
  aggmfinalfn: string;
  aggfinalextra: boolean;
  aggmfinalextra: boolean;
  aggfinalmodify: string;
  aggmfinalmodify: string;
  aggsortop: number;
  aggtranstype: number;
  aggtransspace: number;
  aggmtranstype: number;
  aggmtransspace: number;
  agginitval: string | null;
  aggminitval: string | null;
}

export interface PgCatalogPgAm {
  oid: number;
  amname: string;
  amhandler: string;
  amtype: string;
}

export interface PgCatalogPgAmop {
  oid: number;
  amopfamily: number;
  amoplefttype: number;
  amoprighttype: number;
  amopstrategy: number;
  amoppurpose: string;
  amopopr: number;
  amopmethod: number;
  amopsortfamily: number;
}

export interface PgCatalogPgAmproc {
  oid: number;
  amprocfamily: number;
  amproclefttype: number;
  amprocrighttype: number;
  amprocnum: number;
  amproc: string;
}

export interface PgCatalogPgAttrdef {
  oid: number;
  adrelid: number;
  adnum: number;
  adbin: string;
}

export interface PgCatalogPgAttribute {
  attrelid: number;
  attname: string;
  atttypid: number;
  attstattarget: number;
  attlen: number;
  attnum: number;
  attndims: number;
  atttypmod: number;
  attbyval: boolean;
  attstorage: string;
  attalign: string;
  attnotnull: boolean;
  atthasdef: boolean;
  atthasmissing: boolean;
  attidentity: string;
  attgenerated: string;
  attisdropped: boolean;
  attislocal: boolean;
  attinhcount: number;
  attcollation: number;
  attacl: string[] | null;
  attoptions: string[] | null;
  attfdwoptions: string[] | null;
  attmissingval: string | null;
}

export interface PgCatalogPgAuthid {
  oid: number;
  rolname: string;
  rolsuper: boolean;
  rolinherit: boolean;
  rolcreaterole: boolean;
  rolcreatedb: boolean;
  rolcanlogin: boolean;
  rolreplication: boolean;
  rolbypassrls: boolean;
  rolconnlimit: number;
  rolpassword: string | null;
  rolvaliduntil: Timestamp | null;
}

export interface PgCatalogPgAuthMembers {
  roleid: number;
  member: number;
  grantor: number;
  admin_option: boolean;
}

export interface PgCatalogPgAvailableExtensions {
  name: string | null;
  default_version: string | null;
  installed_version: string | null;
  comment: string | null;
}

export interface PgCatalogPgAvailableExtensionVersions {
  name: string | null;
  version: string | null;
  installed: boolean | null;
  superuser: boolean | null;
  trusted: boolean | null;
  relocatable: boolean | null;
  schema: string | null;
  requires: string[] | null;
  comment: string | null;
}

export interface PgCatalogPgCast {
  oid: number;
  castsource: number;
  casttarget: number;
  castfunc: number;
  castcontext: string;
  castmethod: string;
}

export interface PgCatalogPgClass {
  oid: number;
  relname: string;
  relnamespace: number;
  reltype: number;
  reloftype: number;
  relowner: number;
  relam: number;
  relfilenode: number;
  reltablespace: number;
  relpages: number;
  reltuples: number;
  relallvisible: number;
  reltoastrelid: number;
  relhasindex: boolean;
  relisshared: boolean;
  relpersistence: string;
  relkind: string;
  relnatts: number;
  relchecks: number;
  relhasrules: boolean;
  relhastriggers: boolean;
  relhassubclass: boolean;
  relrowsecurity: boolean;
  relforcerowsecurity: boolean;
  relispopulated: boolean;
  relreplident: string;
  relispartition: boolean;
  relrewrite: number;
  relfrozenxid: string;
  relminmxid: string;
  relacl: string[] | null;
  reloptions: string[] | null;
  relpartbound: string | null;
}

export interface PgCatalogPgCollation {
  oid: number;
  collname: string;
  collnamespace: number;
  collowner: number;
  collprovider: string;
  collisdeterministic: boolean;
  collencoding: number;
  collcollate: string;
  collctype: string;
  collversion: string | null;
}

export interface PgCatalogPgConfig {
  name: string | null;
  setting: string | null;
}

export interface PgCatalogPgConstraint {
  oid: number;
  conname: string;
  connamespace: number;
  contype: string;
  condeferrable: boolean;
  condeferred: boolean;
  convalidated: boolean;
  conrelid: number;
  contypid: number;
  conindid: number;
  conparentid: number;
  confrelid: number;
  confupdtype: string;
  confdeltype: string;
  confmatchtype: string;
  conislocal: boolean;
  coninhcount: number;
  connoinherit: boolean;
  conkey: number[] | null;
  confkey: number[] | null;
  conpfeqop: number[] | null;
  conppeqop: number[] | null;
  conffeqop: number[] | null;
  conexclop: number[] | null;
  conbin: string | null;
}

export interface PgCatalogPgConversion {
  oid: number;
  conname: string;
  connamespace: number;
  conowner: number;
  conforencoding: number;
  contoencoding: number;
  conproc: string;
  condefault: boolean;
}

export interface PgCatalogPgCursors {
  name: string | null;
  statement: string | null;
  is_holdable: boolean | null;
  is_binary: boolean | null;
  is_scrollable: boolean | null;
  creation_time: Timestamp | null;
}

export interface PgCatalogPgDatabase {
  oid: number;
  datname: string;
  datdba: number;
  encoding: number;
  datcollate: string;
  datctype: string;
  datistemplate: boolean;
  datallowconn: boolean;
  datconnlimit: number;
  datlastsysoid: number;
  datfrozenxid: string;
  datminmxid: string;
  dattablespace: number;
  datacl: string[] | null;
}

export interface PgCatalogPgDbRoleSetting {
  setdatabase: number;
  setrole: number;
  setconfig: string[] | null;
}

export interface PgCatalogPgDefaultAcl {
  oid: number;
  defaclrole: number;
  defaclnamespace: number;
  defaclobjtype: string;
  defaclacl: string[];
}

export interface PgCatalogPgDepend {
  classid: number;
  objid: number;
  objsubid: number;
  refclassid: number;
  refobjid: number;
  refobjsubid: number;
  deptype: string;
}

export interface PgCatalogPgDescription {
  objoid: number;
  classoid: number;
  objsubid: number;
  description: string;
}

export interface PgCatalogPgEnum {
  oid: number;
  enumtypid: number;
  enumsortorder: number;
  enumlabel: string;
}

export interface PgCatalogPgEventTrigger {
  oid: number;
  evtname: string;
  evtevent: string;
  evtowner: number;
  evtfoid: number;
  evtenabled: string;
  evttags: string[] | null;
}

export interface PgCatalogPgExtension {
  oid: number;
  extname: string;
  extowner: number;
  extnamespace: number;
  extrelocatable: boolean;
  extversion: string;
  extconfig: number[] | null;
  extcondition: string[] | null;
}

export interface PgCatalogPgFileSettings {
  sourcefile: string | null;
  sourceline: number | null;
  seqno: number | null;
  name: string | null;
  setting: string | null;
  applied: boolean | null;
  error: string | null;
}

export interface PgCatalogPgForeignDataWrapper {
  oid: number;
  fdwname: string;
  fdwowner: number;
  fdwhandler: number;
  fdwvalidator: number;
  fdwacl: string[] | null;
  fdwoptions: string[] | null;
}

export interface PgCatalogPgForeignServer {
  oid: number;
  srvname: string;
  srvowner: number;
  srvfdw: number;
  srvtype: string | null;
  srvversion: string | null;
  srvacl: string[] | null;
  srvoptions: string[] | null;
}

export interface PgCatalogPgForeignTable {
  ftrelid: number;
  ftserver: number;
  ftoptions: string[] | null;
}

export interface PgCatalogPgGroup {
  groname: string | null;
  grosysid: number | null;
  grolist: number[] | null;
}

export interface PgCatalogPgHbaFileRules {
  line_number: number | null;
  type: string | null;
  database: string[] | null;
  user_name: string[] | null;
  address: string | null;
  netmask: string | null;
  auth_method: string | null;
  options: string[] | null;
  error: string | null;
}

export interface PgCatalogPgIndex {
  indexrelid: number;
  indrelid: number;
  indnatts: number;
  indnkeyatts: number;
  indisunique: boolean;
  indisprimary: boolean;
  indisexclusion: boolean;
  indimmediate: boolean;
  indisclustered: boolean;
  indisvalid: boolean;
  indcheckxmin: boolean;
  indisready: boolean;
  indislive: boolean;
  indisreplident: boolean;
  indkey: string;
  indcollation: string;
  indclass: string;
  indoption: string;
  indexprs: string | null;
  indpred: string | null;
}

export interface PgCatalogPgIndexes {
  schemaname: string | null;
  tablename: string | null;
  indexname: string | null;
  tablespace: string | null;
  indexdef: string | null;
}

export interface PgCatalogPgInherits {
  inhrelid: number;
  inhparent: number;
  inhseqno: number;
}

export interface PgCatalogPgInitPrivs {
  objoid: number;
  classoid: number;
  objsubid: number;
  privtype: string;
  initprivs: string[];
}

export interface PgCatalogPgLanguage {
  oid: number;
  lanname: string;
  lanowner: number;
  lanispl: boolean;
  lanpltrusted: boolean;
  lanplcallfoid: number;
  laninline: number;
  lanvalidator: number;
  lanacl: string[] | null;
}

export interface PgCatalogPgLargeobject {
  loid: number;
  pageno: number;
  data: Buffer;
}

export interface PgCatalogPgLargeobjectMetadata {
  oid: number;
  lomowner: number;
  lomacl: string[] | null;
}

export interface PgCatalogPgLocks {
  locktype: string | null;
  database: number | null;
  relation: number | null;
  page: number | null;
  tuple: number | null;
  virtualxid: string | null;
  transactionid: string | null;
  classid: number | null;
  objid: number | null;
  objsubid: number | null;
  virtualtransaction: string | null;
  pid: number | null;
  mode: string | null;
  granted: boolean | null;
  fastpath: boolean | null;
}

export interface PgCatalogPgMatviews {
  schemaname: string | null;
  matviewname: string | null;
  matviewowner: string | null;
  tablespace: string | null;
  hasindexes: boolean | null;
  ispopulated: boolean | null;
  definition: string | null;
}

export interface PgCatalogPgNamespace {
  oid: number;
  nspname: string;
  nspowner: number;
  nspacl: string[] | null;
}

export interface PgCatalogPgOpclass {
  oid: number;
  opcmethod: number;
  opcname: string;
  opcnamespace: number;
  opcowner: number;
  opcfamily: number;
  opcintype: number;
  opcdefault: boolean;
  opckeytype: number;
}

export interface PgCatalogPgOperator {
  oid: number;
  oprname: string;
  oprnamespace: number;
  oprowner: number;
  oprkind: string;
  oprcanmerge: boolean;
  oprcanhash: boolean;
  oprleft: number;
  oprright: number;
  oprresult: number;
  oprcom: number;
  oprnegate: number;
  oprcode: string;
  oprrest: string;
  oprjoin: string;
}

export interface PgCatalogPgOpfamily {
  oid: number;
  opfmethod: number;
  opfname: string;
  opfnamespace: number;
  opfowner: number;
}

export interface PgCatalogPgPartitionedTable {
  partrelid: number;
  partstrat: string;
  partnatts: number;
  partdefid: number;
  partattrs: string;
  partclass: string;
  partcollation: string;
  partexprs: string | null;
}

export interface PgCatalogPgPolicies {
  schemaname: string | null;
  tablename: string | null;
  policyname: string | null;
  permissive: string | null;
  roles: string[] | null;
  cmd: string | null;
  qual: string | null;
  with_check: string | null;
}

export interface PgCatalogPgPolicy {
  oid: number;
  polname: string;
  polrelid: number;
  polcmd: string;
  polpermissive: boolean;
  polroles: number[];
  polqual: string | null;
  polwithcheck: string | null;
}

export interface PgCatalogPgPreparedStatements {
  name: string | null;
  statement: string | null;
  prepare_time: Timestamp | null;
  parameter_types: string[] | null;
  from_sql: boolean | null;
}

export interface PgCatalogPgPreparedXacts {
  transaction: string | null;
  gid: string | null;
  prepared: Timestamp | null;
  owner: string | null;
  database: string | null;
}

export interface PgCatalogPgProc {
  oid: number;
  proname: string;
  pronamespace: number;
  proowner: number;
  prolang: number;
  procost: number;
  prorows: number;
  provariadic: number;
  prosupport: string;
  prokind: string;
  prosecdef: boolean;
  proleakproof: boolean;
  proisstrict: boolean;
  proretset: boolean;
  provolatile: string;
  proparallel: string;
  pronargs: number;
  pronargdefaults: number;
  prorettype: number;
  proargtypes: string;
  proallargtypes: number[] | null;
  proargmodes: string[] | null;
  proargnames: string[] | null;
  proargdefaults: string | null;
  protrftypes: number[] | null;
  prosrc: string;
  probin: string | null;
  proconfig: string[] | null;
  proacl: string[] | null;
}

export interface PgCatalogPgPublication {
  oid: number;
  pubname: string;
  pubowner: number;
  puballtables: boolean;
  pubinsert: boolean;
  pubupdate: boolean;
  pubdelete: boolean;
  pubtruncate: boolean;
  pubviaroot: boolean;
}

export interface PgCatalogPgPublicationRel {
  oid: number;
  prpubid: number;
  prrelid: number;
}

export interface PgCatalogPgPublicationTables {
  pubname: string | null;
  schemaname: string | null;
  tablename: string | null;
}

export interface PgCatalogPgRange {
  rngtypid: number;
  rngsubtype: number;
  rngcollation: number;
  rngsubopc: number;
  rngcanonical: string;
  rngsubdiff: string;
}

export interface PgCatalogPgReplicationOrigin {
  roident: number;
  roname: string;
}

export interface PgCatalogPgReplicationOriginStatus {
  local_id: number | null;
  external_id: string | null;
  remote_lsn: string | null;
  local_lsn: string | null;
}

export interface PgCatalogPgReplicationSlots {
  slot_name: string | null;
  plugin: string | null;
  slot_type: string | null;
  datoid: number | null;
  database: string | null;
  temporary: boolean | null;
  active: boolean | null;
  active_pid: number | null;
  xmin: string | null;
  catalog_xmin: string | null;
  restart_lsn: string | null;
  confirmed_flush_lsn: string | null;
  wal_status: string | null;
  safe_wal_size: Int8 | null;
}

export interface PgCatalogPgRewrite {
  oid: number;
  rulename: string;
  ev_class: number;
  ev_type: string;
  ev_enabled: string;
  is_instead: boolean;
  ev_qual: string;
  ev_action: string;
}

export interface PgCatalogPgRoles {
  rolname: string | null;
  rolsuper: boolean | null;
  rolinherit: boolean | null;
  rolcreaterole: boolean | null;
  rolcreatedb: boolean | null;
  rolcanlogin: boolean | null;
  rolreplication: boolean | null;
  rolconnlimit: number | null;
  rolpassword: string | null;
  rolvaliduntil: Timestamp | null;
  rolbypassrls: boolean | null;
  rolconfig: string[] | null;
  oid: number | null;
}

export interface PgCatalogPgRules {
  schemaname: string | null;
  tablename: string | null;
  rulename: string | null;
  definition: string | null;
}

export interface PgCatalogPgSeclabel {
  objoid: number;
  classoid: number;
  objsubid: number;
  provider: string;
  label: string;
}

export interface PgCatalogPgSeclabels {
  objoid: number | null;
  classoid: number | null;
  objsubid: number | null;
  objtype: string | null;
  objnamespace: number | null;
  objname: string | null;
  provider: string | null;
  label: string | null;
}

export interface PgCatalogPgSequence {
  seqrelid: number;
  seqtypid: number;
  seqstart: Int8;
  seqincrement: Int8;
  seqmax: Int8;
  seqmin: Int8;
  seqcache: Int8;
  seqcycle: boolean;
}

export interface PgCatalogPgSequences {
  schemaname: string | null;
  sequencename: string | null;
  sequenceowner: string | null;
  data_type: string | null;
  start_value: Int8 | null;
  min_value: Int8 | null;
  max_value: Int8 | null;
  increment_by: Int8 | null;
  cycle: boolean | null;
  cache_size: Int8 | null;
  last_value: Int8 | null;
}

export interface PgCatalogPgSettings {
  name: string | null;
  setting: string | null;
  unit: string | null;
  category: string | null;
  short_desc: string | null;
  extra_desc: string | null;
  context: string | null;
  vartype: string | null;
  source: string | null;
  min_val: string | null;
  max_val: string | null;
  enumvals: string[] | null;
  boot_val: string | null;
  reset_val: string | null;
  sourcefile: string | null;
  sourceline: number | null;
  pending_restart: boolean | null;
}

export interface PgCatalogPgShadow {
  usename: string | null;
  usesysid: number | null;
  usecreatedb: boolean | null;
  usesuper: boolean | null;
  userepl: boolean | null;
  usebypassrls: boolean | null;
  passwd: string | null;
  valuntil: Timestamp | null;
  useconfig: string[] | null;
}

export interface PgCatalogPgShdepend {
  dbid: number;
  classid: number;
  objid: number;
  objsubid: number;
  refclassid: number;
  refobjid: number;
  deptype: string;
}

export interface PgCatalogPgShdescription {
  objoid: number;
  classoid: number;
  description: string;
}

export interface PgCatalogPgShmemAllocations {
  name: string | null;
  off: Int8 | null;
  size: Int8 | null;
  allocated_size: Int8 | null;
}

export interface PgCatalogPgShseclabel {
  objoid: number;
  classoid: number;
  provider: string;
  label: string;
}

export interface PgCatalogPgStatActivity {
  datid: number | null;
  datname: string | null;
  pid: number | null;
  leader_pid: number | null;
  usesysid: number | null;
  usename: string | null;
  application_name: string | null;
  client_addr: string | null;
  client_hostname: string | null;
  client_port: number | null;
  backend_start: Timestamp | null;
  xact_start: Timestamp | null;
  query_start: Timestamp | null;
  state_change: Timestamp | null;
  wait_event_type: string | null;
  wait_event: string | null;
  state: string | null;
  backend_xid: string | null;
  backend_xmin: string | null;
  query: string | null;
  backend_type: string | null;
}

export interface PgCatalogPgStatAllIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_scan: Int8 | null;
  idx_tup_read: Int8 | null;
  idx_tup_fetch: Int8 | null;
}

export interface PgCatalogPgStatAllTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
  n_live_tup: Int8 | null;
  n_dead_tup: Int8 | null;
  n_mod_since_analyze: Int8 | null;
  n_ins_since_vacuum: Int8 | null;
  last_vacuum: Timestamp | null;
  last_autovacuum: Timestamp | null;
  last_analyze: Timestamp | null;
  last_autoanalyze: Timestamp | null;
  vacuum_count: Int8 | null;
  autovacuum_count: Int8 | null;
  analyze_count: Int8 | null;
  autoanalyze_count: Int8 | null;
}

export interface PgCatalogPgStatArchiver {
  archived_count: Int8 | null;
  last_archived_wal: string | null;
  last_archived_time: Timestamp | null;
  failed_count: Int8 | null;
  last_failed_wal: string | null;
  last_failed_time: Timestamp | null;
  stats_reset: Timestamp | null;
}

export interface PgCatalogPgStatBgwriter {
  checkpoints_timed: Int8 | null;
  checkpoints_req: Int8 | null;
  checkpoint_write_time: number | null;
  checkpoint_sync_time: number | null;
  buffers_checkpoint: Int8 | null;
  buffers_clean: Int8 | null;
  maxwritten_clean: Int8 | null;
  buffers_backend: Int8 | null;
  buffers_backend_fsync: Int8 | null;
  buffers_alloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface PgCatalogPgStatDatabase {
  datid: number | null;
  datname: string | null;
  numbackends: number | null;
  xact_commit: Int8 | null;
  xact_rollback: Int8 | null;
  blks_read: Int8 | null;
  blks_hit: Int8 | null;
  tup_returned: Int8 | null;
  tup_fetched: Int8 | null;
  tup_inserted: Int8 | null;
  tup_updated: Int8 | null;
  tup_deleted: Int8 | null;
  conflicts: Int8 | null;
  temp_files: Int8 | null;
  temp_bytes: Int8 | null;
  deadlocks: Int8 | null;
  checksum_failures: Int8 | null;
  checksum_last_failure: Timestamp | null;
  blk_read_time: number | null;
  blk_write_time: number | null;
  stats_reset: Timestamp | null;
}

export interface PgCatalogPgStatDatabaseConflicts {
  datid: number | null;
  datname: string | null;
  confl_tablespace: Int8 | null;
  confl_lock: Int8 | null;
  confl_snapshot: Int8 | null;
  confl_bufferpin: Int8 | null;
  confl_deadlock: Int8 | null;
}

export interface PgCatalogPgStatGssapi {
  pid: number | null;
  gss_authenticated: boolean | null;
  principal: string | null;
  encrypted: boolean | null;
}

export interface PgCatalogPgStatioAllIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioAllSequences {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  blks_read: Int8 | null;
  blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioAllTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  heap_blks_read: Int8 | null;
  heap_blks_hit: Int8 | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
  toast_blks_read: Int8 | null;
  toast_blks_hit: Int8 | null;
  tidx_blks_read: Int8 | null;
  tidx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioSysIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioSysSequences {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  blks_read: Int8 | null;
  blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioSysTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  heap_blks_read: Int8 | null;
  heap_blks_hit: Int8 | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
  toast_blks_read: Int8 | null;
  toast_blks_hit: Int8 | null;
  tidx_blks_read: Int8 | null;
  tidx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioUserIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioUserSequences {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  blks_read: Int8 | null;
  blks_hit: Int8 | null;
}

export interface PgCatalogPgStatioUserTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  heap_blks_read: Int8 | null;
  heap_blks_hit: Int8 | null;
  idx_blks_read: Int8 | null;
  idx_blks_hit: Int8 | null;
  toast_blks_read: Int8 | null;
  toast_blks_hit: Int8 | null;
  tidx_blks_read: Int8 | null;
  tidx_blks_hit: Int8 | null;
}

export interface PgCatalogPgStatistic {
  starelid: number;
  staattnum: number;
  stainherit: boolean;
  stanullfrac: number;
  stawidth: number;
  stadistinct: number;
  stakind1: number;
  stakind2: number;
  stakind3: number;
  stakind4: number;
  stakind5: number;
  staop1: number;
  staop2: number;
  staop3: number;
  staop4: number;
  staop5: number;
  stacoll1: number;
  stacoll2: number;
  stacoll3: number;
  stacoll4: number;
  stacoll5: number;
  stanumbers1: number[] | null;
  stanumbers2: number[] | null;
  stanumbers3: number[] | null;
  stanumbers4: number[] | null;
  stanumbers5: number[] | null;
  stavalues1: string | null;
  stavalues2: string | null;
  stavalues3: string | null;
  stavalues4: string | null;
  stavalues5: string | null;
}

export interface PgCatalogPgStatisticExt {
  oid: number;
  stxrelid: number;
  stxname: string;
  stxnamespace: number;
  stxowner: number;
  stxstattarget: number;
  stxkeys: string;
  stxkind: string[];
}

export interface PgCatalogPgStatisticExtData {
  stxoid: number;
  stxdndistinct: string | null;
  stxddependencies: string | null;
  stxdmcv: string | null;
}

export interface PgCatalogPgStatProgressAnalyze {
  pid: number | null;
  datid: number | null;
  datname: string | null;
  relid: number | null;
  phase: string | null;
  sample_blks_total: Int8 | null;
  sample_blks_scanned: Int8 | null;
  ext_stats_total: Int8 | null;
  ext_stats_computed: Int8 | null;
  child_tables_total: Int8 | null;
  child_tables_done: Int8 | null;
  current_child_table_relid: number | null;
}

export interface PgCatalogPgStatProgressBasebackup {
  pid: number | null;
  phase: string | null;
  backup_total: Int8 | null;
  backup_streamed: Int8 | null;
  tablespaces_total: Int8 | null;
  tablespaces_streamed: Int8 | null;
}

export interface PgCatalogPgStatProgressCluster {
  pid: number | null;
  datid: number | null;
  datname: string | null;
  relid: number | null;
  command: string | null;
  phase: string | null;
  cluster_index_relid: number | null;
  heap_tuples_scanned: Int8 | null;
  heap_tuples_written: Int8 | null;
  heap_blks_total: Int8 | null;
  heap_blks_scanned: Int8 | null;
  index_rebuild_count: Int8 | null;
}

export interface PgCatalogPgStatProgressCreateIndex {
  pid: number | null;
  datid: number | null;
  datname: string | null;
  relid: number | null;
  index_relid: number | null;
  command: string | null;
  phase: string | null;
  lockers_total: Int8 | null;
  lockers_done: Int8 | null;
  current_locker_pid: Int8 | null;
  blocks_total: Int8 | null;
  blocks_done: Int8 | null;
  tuples_total: Int8 | null;
  tuples_done: Int8 | null;
  partitions_total: Int8 | null;
  partitions_done: Int8 | null;
}

export interface PgCatalogPgStatProgressVacuum {
  pid: number | null;
  datid: number | null;
  datname: string | null;
  relid: number | null;
  phase: string | null;
  heap_blks_total: Int8 | null;
  heap_blks_scanned: Int8 | null;
  heap_blks_vacuumed: Int8 | null;
  index_vacuum_count: Int8 | null;
  max_dead_tuples: Int8 | null;
  num_dead_tuples: Int8 | null;
}

export interface PgCatalogPgStatReplication {
  pid: number | null;
  usesysid: number | null;
  usename: string | null;
  application_name: string | null;
  client_addr: string | null;
  client_hostname: string | null;
  client_port: number | null;
  backend_start: Timestamp | null;
  backend_xmin: string | null;
  state: string | null;
  sent_lsn: string | null;
  write_lsn: string | null;
  flush_lsn: string | null;
  replay_lsn: string | null;
  write_lag: Interval | null;
  flush_lag: Interval | null;
  replay_lag: Interval | null;
  sync_priority: number | null;
  sync_state: string | null;
  reply_time: Timestamp | null;
}

export interface PgCatalogPgStats {
  schemaname: string | null;
  tablename: string | null;
  attname: string | null;
  inherited: boolean | null;
  null_frac: number | null;
  avg_width: number | null;
  n_distinct: number | null;
  most_common_vals: string | null;
  most_common_freqs: number[] | null;
  histogram_bounds: string | null;
  correlation: number | null;
  most_common_elems: string | null;
  most_common_elem_freqs: number[] | null;
  elem_count_histogram: number[] | null;
}

export interface PgCatalogPgStatsExt {
  schemaname: string | null;
  tablename: string | null;
  statistics_schemaname: string | null;
  statistics_name: string | null;
  statistics_owner: string | null;
  attnames: string[] | null;
  kinds: string[] | null;
  n_distinct: string | null;
  dependencies: string | null;
  most_common_vals: string[] | null;
  most_common_val_nulls: boolean[] | null;
  most_common_freqs: number[] | null;
  most_common_base_freqs: number[] | null;
}

export interface PgCatalogPgStatSlru {
  name: string | null;
  blks_zeroed: Int8 | null;
  blks_hit: Int8 | null;
  blks_read: Int8 | null;
  blks_written: Int8 | null;
  blks_exists: Int8 | null;
  flushes: Int8 | null;
  truncates: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface PgCatalogPgStatSsl {
  pid: number | null;
  ssl: boolean | null;
  version: string | null;
  cipher: string | null;
  bits: number | null;
  compression: boolean | null;
  client_dn: string | null;
  client_serial: Numeric | null;
  issuer_dn: string | null;
}

export interface PgCatalogPgStatSubscription {
  subid: number | null;
  subname: string | null;
  pid: number | null;
  relid: number | null;
  received_lsn: string | null;
  last_msg_send_time: Timestamp | null;
  last_msg_receipt_time: Timestamp | null;
  latest_end_lsn: string | null;
  latest_end_time: Timestamp | null;
}

export interface PgCatalogPgStatSysIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_scan: Int8 | null;
  idx_tup_read: Int8 | null;
  idx_tup_fetch: Int8 | null;
}

export interface PgCatalogPgStatSysTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
  n_live_tup: Int8 | null;
  n_dead_tup: Int8 | null;
  n_mod_since_analyze: Int8 | null;
  n_ins_since_vacuum: Int8 | null;
  last_vacuum: Timestamp | null;
  last_autovacuum: Timestamp | null;
  last_analyze: Timestamp | null;
  last_autoanalyze: Timestamp | null;
  vacuum_count: Int8 | null;
  autovacuum_count: Int8 | null;
  analyze_count: Int8 | null;
  autoanalyze_count: Int8 | null;
}

export interface PgCatalogPgStatUserFunctions {
  funcid: number | null;
  schemaname: string | null;
  funcname: string | null;
  calls: Int8 | null;
  total_time: number | null;
  self_time: number | null;
}

export interface PgCatalogPgStatUserIndexes {
  relid: number | null;
  indexrelid: number | null;
  schemaname: string | null;
  relname: string | null;
  indexrelname: string | null;
  idx_scan: Int8 | null;
  idx_tup_read: Int8 | null;
  idx_tup_fetch: Int8 | null;
}

export interface PgCatalogPgStatUserTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
  n_live_tup: Int8 | null;
  n_dead_tup: Int8 | null;
  n_mod_since_analyze: Int8 | null;
  n_ins_since_vacuum: Int8 | null;
  last_vacuum: Timestamp | null;
  last_autovacuum: Timestamp | null;
  last_analyze: Timestamp | null;
  last_autoanalyze: Timestamp | null;
  vacuum_count: Int8 | null;
  autovacuum_count: Int8 | null;
  analyze_count: Int8 | null;
  autoanalyze_count: Int8 | null;
}

export interface PgCatalogPgStatWalReceiver {
  pid: number | null;
  status: string | null;
  receive_start_lsn: string | null;
  receive_start_tli: number | null;
  written_lsn: string | null;
  flushed_lsn: string | null;
  received_tli: number | null;
  last_msg_send_time: Timestamp | null;
  last_msg_receipt_time: Timestamp | null;
  latest_end_lsn: string | null;
  latest_end_time: Timestamp | null;
  slot_name: string | null;
  sender_host: string | null;
  sender_port: number | null;
  conninfo: string | null;
}

export interface PgCatalogPgStatXactAllTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
}

export interface PgCatalogPgStatXactSysTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
}

export interface PgCatalogPgStatXactUserFunctions {
  funcid: number | null;
  schemaname: string | null;
  funcname: string | null;
  calls: Int8 | null;
  total_time: number | null;
  self_time: number | null;
}

export interface PgCatalogPgStatXactUserTables {
  relid: number | null;
  schemaname: string | null;
  relname: string | null;
  seq_scan: Int8 | null;
  seq_tup_read: Int8 | null;
  idx_scan: Int8 | null;
  idx_tup_fetch: Int8 | null;
  n_tup_ins: Int8 | null;
  n_tup_upd: Int8 | null;
  n_tup_del: Int8 | null;
  n_tup_hot_upd: Int8 | null;
}

export interface PgCatalogPgSubscription {
  oid: number;
  subdbid: number;
  subname: string;
  subowner: number;
  subenabled: boolean;
  subconninfo: string;
  subslotname: string | null;
  subsynccommit: string;
  subpublications: string[];
}

export interface PgCatalogPgSubscriptionRel {
  srsubid: number;
  srrelid: number;
  srsubstate: string;
  srsublsn: string | null;
}

export interface PgCatalogPgTables {
  schemaname: string | null;
  tablename: string | null;
  tableowner: string | null;
  tablespace: string | null;
  hasindexes: boolean | null;
  hasrules: boolean | null;
  hastriggers: boolean | null;
  rowsecurity: boolean | null;
}

export interface PgCatalogPgTablespace {
  oid: number;
  spcname: string;
  spcowner: number;
  spcacl: string[] | null;
  spcoptions: string[] | null;
}

export interface PgCatalogPgTimezoneAbbrevs {
  abbrev: string | null;
  utc_offset: Interval | null;
  is_dst: boolean | null;
}

export interface PgCatalogPgTimezoneNames {
  name: string | null;
  abbrev: string | null;
  utc_offset: Interval | null;
  is_dst: boolean | null;
}

export interface PgCatalogPgTransform {
  oid: number;
  trftype: number;
  trflang: number;
  trffromsql: string;
  trftosql: string;
}

export interface PgCatalogPgTrigger {
  oid: number;
  tgrelid: number;
  tgparentid: number;
  tgname: string;
  tgfoid: number;
  tgtype: number;
  tgenabled: string;
  tgisinternal: boolean;
  tgconstrrelid: number;
  tgconstrindid: number;
  tgconstraint: number;
  tgdeferrable: boolean;
  tginitdeferred: boolean;
  tgnargs: number;
  tgattr: string;
  tgargs: Buffer;
  tgqual: string | null;
  tgoldtable: string | null;
  tgnewtable: string | null;
}

export interface PgCatalogPgTsConfig {
  oid: number;
  cfgname: string;
  cfgnamespace: number;
  cfgowner: number;
  cfgparser: number;
}

export interface PgCatalogPgTsConfigMap {
  mapcfg: number;
  maptokentype: number;
  mapseqno: number;
  mapdict: number;
}

export interface PgCatalogPgTsDict {
  oid: number;
  dictname: string;
  dictnamespace: number;
  dictowner: number;
  dicttemplate: number;
  dictinitoption: string | null;
}

export interface PgCatalogPgTsParser {
  oid: number;
  prsname: string;
  prsnamespace: number;
  prsstart: string;
  prstoken: string;
  prsend: string;
  prsheadline: string;
  prslextype: string;
}

export interface PgCatalogPgTsTemplate {
  oid: number;
  tmplname: string;
  tmplnamespace: number;
  tmplinit: string;
  tmpllexize: string;
}

export interface PgCatalogPgType {
  oid: number;
  typname: string;
  typnamespace: number;
  typowner: number;
  typlen: number;
  typbyval: boolean;
  typtype: string;
  typcategory: string;
  typispreferred: boolean;
  typisdefined: boolean;
  typdelim: string;
  typrelid: number;
  typelem: number;
  typarray: number;
  typinput: string;
  typoutput: string;
  typreceive: string;
  typsend: string;
  typmodin: string;
  typmodout: string;
  typanalyze: string;
  typalign: string;
  typstorage: string;
  typnotnull: boolean;
  typbasetype: number;
  typtypmod: number;
  typndims: number;
  typcollation: number;
  typdefaultbin: string | null;
  typdefault: string | null;
  typacl: string[] | null;
}

export interface PgCatalogPgUser {
  usename: string | null;
  usesysid: number | null;
  usecreatedb: boolean | null;
  usesuper: boolean | null;
  userepl: boolean | null;
  usebypassrls: boolean | null;
  passwd: string | null;
  valuntil: Timestamp | null;
  useconfig: string[] | null;
}

export interface PgCatalogPgUserMapping {
  oid: number;
  umuser: number;
  umserver: number;
  umoptions: string[] | null;
}

export interface PgCatalogPgUserMappings {
  umid: number | null;
  srvid: number | null;
  srvname: string | null;
  umuser: number | null;
  usename: string | null;
  umoptions: string[] | null;
}

export interface PgCatalogPgViews {
  schemaname: string | null;
  viewname: string | null;
  viewowner: string | null;
  definition: string | null;
}

export interface PGMetaDB {
  "information_schema._pg_foreign_data_wrappers": InformationSchemaPgForeignDataWrappers;
  "information_schema._pg_foreign_servers": InformationSchemaPgForeignServers;
  "information_schema._pg_foreign_table_columns": InformationSchemaPgForeignTableColumns;
  "information_schema._pg_foreign_tables": InformationSchemaPgForeignTables;
  "information_schema._pg_user_mappings": InformationSchemaPgUserMappings;
  "information_schema.administrable_role_authorizations": InformationSchemaAdministrableRoleAuthorizations;
  "information_schema.applicable_roles": InformationSchemaApplicableRoles;
  "information_schema.attributes": InformationSchemaAttributes;
  "information_schema.character_sets": InformationSchemaCharacterSets;
  "information_schema.check_constraint_routine_usage": InformationSchemaCheckConstraintRoutineUsage;
  "information_schema.check_constraints": InformationSchemaCheckConstraints;
  "information_schema.collation_character_set_applicability": InformationSchemaCollationCharacterSetApplicability;
  "information_schema.collations": InformationSchemaCollations;
  "information_schema.column_column_usage": InformationSchemaColumnColumnUsage;
  "information_schema.column_domain_usage": InformationSchemaColumnDomainUsage;
  "information_schema.column_options": InformationSchemaColumnOptions;
  "information_schema.column_privileges": InformationSchemaColumnPrivileges;
  "information_schema.column_udt_usage": InformationSchemaColumnUdtUsage;
  "information_schema.columns": InformationSchemaColumns;
  "information_schema.constraint_column_usage": InformationSchemaConstraintColumnUsage;
  "information_schema.constraint_table_usage": InformationSchemaConstraintTableUsage;
  "information_schema.data_type_privileges": InformationSchemaDataTypePrivileges;
  "information_schema.domain_constraints": InformationSchemaDomainConstraints;
  "information_schema.domain_udt_usage": InformationSchemaDomainUdtUsage;
  "information_schema.domains": InformationSchemaDomains;
  "information_schema.element_types": InformationSchemaElementTypes;
  "information_schema.enabled_roles": InformationSchemaEnabledRoles;
  "information_schema.foreign_data_wrapper_options": InformationSchemaForeignDataWrapperOptions;
  "information_schema.foreign_data_wrappers": InformationSchemaForeignDataWrappers;
  "information_schema.foreign_server_options": InformationSchemaForeignServerOptions;
  "information_schema.foreign_servers": InformationSchemaForeignServers;
  "information_schema.foreign_table_options": InformationSchemaForeignTableOptions;
  "information_schema.foreign_tables": InformationSchemaForeignTables;
  "information_schema.information_schema_catalog_name": InformationSchemaInformationSchemaCatalogName;
  "information_schema.key_column_usage": InformationSchemaKeyColumnUsage;
  "information_schema.parameters": InformationSchemaParameters;
  "information_schema.referential_constraints": InformationSchemaReferentialConstraints;
  "information_schema.role_column_grants": InformationSchemaRoleColumnGrants;
  "information_schema.role_routine_grants": InformationSchemaRoleRoutineGrants;
  "information_schema.role_table_grants": InformationSchemaRoleTableGrants;
  "information_schema.role_udt_grants": InformationSchemaRoleUdtGrants;
  "information_schema.role_usage_grants": InformationSchemaRoleUsageGrants;
  "information_schema.routine_privileges": InformationSchemaRoutinePrivileges;
  "information_schema.routines": InformationSchemaRoutines;
  "information_schema.schemata": InformationSchemaSchemata;
  "information_schema.sequences": InformationSchemaSequences;
  "information_schema.sql_features": InformationSchemaSqlFeatures;
  "information_schema.sql_implementation_info": InformationSchemaSqlImplementationInfo;
  "information_schema.sql_parts": InformationSchemaSqlParts;
  "information_schema.sql_sizing": InformationSchemaSqlSizing;
  "information_schema.table_constraints": InformationSchemaTableConstraints;
  "information_schema.table_privileges": InformationSchemaTablePrivileges;
  "information_schema.tables": InformationSchemaTables;
  "information_schema.transforms": InformationSchemaTransforms;
  "information_schema.triggered_update_columns": InformationSchemaTriggeredUpdateColumns;
  "information_schema.triggers": InformationSchemaTriggers;
  "information_schema.udt_privileges": InformationSchemaUdtPrivileges;
  "information_schema.usage_privileges": InformationSchemaUsagePrivileges;
  "information_schema.user_defined_types": InformationSchemaUserDefinedTypes;
  "information_schema.user_mapping_options": InformationSchemaUserMappingOptions;
  "information_schema.user_mappings": InformationSchemaUserMappings;
  "information_schema.view_column_usage": InformationSchemaViewColumnUsage;
  "information_schema.view_routine_usage": InformationSchemaViewRoutineUsage;
  "information_schema.view_table_usage": InformationSchemaViewTableUsage;
  "information_schema.views": InformationSchemaViews;
  "pg_catalog.pg_aggregate": PgCatalogPgAggregate;
  "pg_catalog.pg_am": PgCatalogPgAm;
  "pg_catalog.pg_amop": PgCatalogPgAmop;
  "pg_catalog.pg_amproc": PgCatalogPgAmproc;
  "pg_catalog.pg_attrdef": PgCatalogPgAttrdef;
  "pg_catalog.pg_attribute": PgCatalogPgAttribute;
  "pg_catalog.pg_auth_members": PgCatalogPgAuthMembers;
  "pg_catalog.pg_authid": PgCatalogPgAuthid;
  "pg_catalog.pg_available_extension_versions": PgCatalogPgAvailableExtensionVersions;
  "pg_catalog.pg_available_extensions": PgCatalogPgAvailableExtensions;
  "pg_catalog.pg_cast": PgCatalogPgCast;
  "pg_catalog.pg_class": PgCatalogPgClass;
  "pg_catalog.pg_collation": PgCatalogPgCollation;
  "pg_catalog.pg_config": PgCatalogPgConfig;
  "pg_catalog.pg_constraint": PgCatalogPgConstraint;
  "pg_catalog.pg_conversion": PgCatalogPgConversion;
  "pg_catalog.pg_cursors": PgCatalogPgCursors;
  "pg_catalog.pg_database": PgCatalogPgDatabase;
  "pg_catalog.pg_db_role_setting": PgCatalogPgDbRoleSetting;
  "pg_catalog.pg_default_acl": PgCatalogPgDefaultAcl;
  "pg_catalog.pg_depend": PgCatalogPgDepend;
  "pg_catalog.pg_description": PgCatalogPgDescription;
  "pg_catalog.pg_enum": PgCatalogPgEnum;
  "pg_catalog.pg_event_trigger": PgCatalogPgEventTrigger;
  "pg_catalog.pg_extension": PgCatalogPgExtension;
  "pg_catalog.pg_file_settings": PgCatalogPgFileSettings;
  "pg_catalog.pg_foreign_data_wrapper": PgCatalogPgForeignDataWrapper;
  "pg_catalog.pg_foreign_server": PgCatalogPgForeignServer;
  "pg_catalog.pg_foreign_table": PgCatalogPgForeignTable;
  "pg_catalog.pg_group": PgCatalogPgGroup;
  "pg_catalog.pg_hba_file_rules": PgCatalogPgHbaFileRules;
  "pg_catalog.pg_index": PgCatalogPgIndex;
  "pg_catalog.pg_indexes": PgCatalogPgIndexes;
  "pg_catalog.pg_inherits": PgCatalogPgInherits;
  "pg_catalog.pg_init_privs": PgCatalogPgInitPrivs;
  "pg_catalog.pg_language": PgCatalogPgLanguage;
  "pg_catalog.pg_largeobject": PgCatalogPgLargeobject;
  "pg_catalog.pg_largeobject_metadata": PgCatalogPgLargeobjectMetadata;
  "pg_catalog.pg_locks": PgCatalogPgLocks;
  "pg_catalog.pg_matviews": PgCatalogPgMatviews;
  "pg_catalog.pg_namespace": PgCatalogPgNamespace;
  "pg_catalog.pg_opclass": PgCatalogPgOpclass;
  "pg_catalog.pg_operator": PgCatalogPgOperator;
  "pg_catalog.pg_opfamily": PgCatalogPgOpfamily;
  "pg_catalog.pg_partitioned_table": PgCatalogPgPartitionedTable;
  "pg_catalog.pg_policies": PgCatalogPgPolicies;
  "pg_catalog.pg_policy": PgCatalogPgPolicy;
  "pg_catalog.pg_prepared_statements": PgCatalogPgPreparedStatements;
  "pg_catalog.pg_prepared_xacts": PgCatalogPgPreparedXacts;
  "pg_catalog.pg_proc": PgCatalogPgProc;
  "pg_catalog.pg_publication": PgCatalogPgPublication;
  "pg_catalog.pg_publication_rel": PgCatalogPgPublicationRel;
  "pg_catalog.pg_publication_tables": PgCatalogPgPublicationTables;
  "pg_catalog.pg_range": PgCatalogPgRange;
  "pg_catalog.pg_replication_origin": PgCatalogPgReplicationOrigin;
  "pg_catalog.pg_replication_origin_status": PgCatalogPgReplicationOriginStatus;
  "pg_catalog.pg_replication_slots": PgCatalogPgReplicationSlots;
  "pg_catalog.pg_rewrite": PgCatalogPgRewrite;
  "pg_catalog.pg_roles": PgCatalogPgRoles;
  "pg_catalog.pg_rules": PgCatalogPgRules;
  "pg_catalog.pg_seclabel": PgCatalogPgSeclabel;
  "pg_catalog.pg_seclabels": PgCatalogPgSeclabels;
  "pg_catalog.pg_sequence": PgCatalogPgSequence;
  "pg_catalog.pg_sequences": PgCatalogPgSequences;
  "pg_catalog.pg_settings": PgCatalogPgSettings;
  "pg_catalog.pg_shadow": PgCatalogPgShadow;
  "pg_catalog.pg_shdepend": PgCatalogPgShdepend;
  "pg_catalog.pg_shdescription": PgCatalogPgShdescription;
  "pg_catalog.pg_shmem_allocations": PgCatalogPgShmemAllocations;
  "pg_catalog.pg_shseclabel": PgCatalogPgShseclabel;
  "pg_catalog.pg_stat_activity": PgCatalogPgStatActivity;
  "pg_catalog.pg_stat_all_indexes": PgCatalogPgStatAllIndexes;
  "pg_catalog.pg_stat_all_tables": PgCatalogPgStatAllTables;
  "pg_catalog.pg_stat_archiver": PgCatalogPgStatArchiver;
  "pg_catalog.pg_stat_bgwriter": PgCatalogPgStatBgwriter;
  "pg_catalog.pg_stat_database": PgCatalogPgStatDatabase;
  "pg_catalog.pg_stat_database_conflicts": PgCatalogPgStatDatabaseConflicts;
  "pg_catalog.pg_stat_gssapi": PgCatalogPgStatGssapi;
  "pg_catalog.pg_stat_progress_analyze": PgCatalogPgStatProgressAnalyze;
  "pg_catalog.pg_stat_progress_basebackup": PgCatalogPgStatProgressBasebackup;
  "pg_catalog.pg_stat_progress_cluster": PgCatalogPgStatProgressCluster;
  "pg_catalog.pg_stat_progress_create_index": PgCatalogPgStatProgressCreateIndex;
  "pg_catalog.pg_stat_progress_vacuum": PgCatalogPgStatProgressVacuum;
  "pg_catalog.pg_stat_replication": PgCatalogPgStatReplication;
  "pg_catalog.pg_stat_slru": PgCatalogPgStatSlru;
  "pg_catalog.pg_stat_ssl": PgCatalogPgStatSsl;
  "pg_catalog.pg_stat_subscription": PgCatalogPgStatSubscription;
  "pg_catalog.pg_stat_sys_indexes": PgCatalogPgStatSysIndexes;
  "pg_catalog.pg_stat_sys_tables": PgCatalogPgStatSysTables;
  "pg_catalog.pg_stat_user_functions": PgCatalogPgStatUserFunctions;
  "pg_catalog.pg_stat_user_indexes": PgCatalogPgStatUserIndexes;
  "pg_catalog.pg_stat_user_tables": PgCatalogPgStatUserTables;
  "pg_catalog.pg_stat_wal_receiver": PgCatalogPgStatWalReceiver;
  "pg_catalog.pg_stat_xact_all_tables": PgCatalogPgStatXactAllTables;
  "pg_catalog.pg_stat_xact_sys_tables": PgCatalogPgStatXactSysTables;
  "pg_catalog.pg_stat_xact_user_functions": PgCatalogPgStatXactUserFunctions;
  "pg_catalog.pg_stat_xact_user_tables": PgCatalogPgStatXactUserTables;
  "pg_catalog.pg_statio_all_indexes": PgCatalogPgStatioAllIndexes;
  "pg_catalog.pg_statio_all_sequences": PgCatalogPgStatioAllSequences;
  "pg_catalog.pg_statio_all_tables": PgCatalogPgStatioAllTables;
  "pg_catalog.pg_statio_sys_indexes": PgCatalogPgStatioSysIndexes;
  "pg_catalog.pg_statio_sys_sequences": PgCatalogPgStatioSysSequences;
  "pg_catalog.pg_statio_sys_tables": PgCatalogPgStatioSysTables;
  "pg_catalog.pg_statio_user_indexes": PgCatalogPgStatioUserIndexes;
  "pg_catalog.pg_statio_user_sequences": PgCatalogPgStatioUserSequences;
  "pg_catalog.pg_statio_user_tables": PgCatalogPgStatioUserTables;
  "pg_catalog.pg_statistic": PgCatalogPgStatistic;
  "pg_catalog.pg_statistic_ext": PgCatalogPgStatisticExt;
  "pg_catalog.pg_statistic_ext_data": PgCatalogPgStatisticExtData;
  "pg_catalog.pg_stats": PgCatalogPgStats;
  "pg_catalog.pg_stats_ext": PgCatalogPgStatsExt;
  "pg_catalog.pg_subscription": PgCatalogPgSubscription;
  "pg_catalog.pg_subscription_rel": PgCatalogPgSubscriptionRel;
  "pg_catalog.pg_tables": PgCatalogPgTables;
  "pg_catalog.pg_tablespace": PgCatalogPgTablespace;
  "pg_catalog.pg_timezone_abbrevs": PgCatalogPgTimezoneAbbrevs;
  "pg_catalog.pg_timezone_names": PgCatalogPgTimezoneNames;
  "pg_catalog.pg_transform": PgCatalogPgTransform;
  "pg_catalog.pg_trigger": PgCatalogPgTrigger;
  "pg_catalog.pg_ts_config": PgCatalogPgTsConfig;
  "pg_catalog.pg_ts_config_map": PgCatalogPgTsConfigMap;
  "pg_catalog.pg_ts_dict": PgCatalogPgTsDict;
  "pg_catalog.pg_ts_parser": PgCatalogPgTsParser;
  "pg_catalog.pg_ts_template": PgCatalogPgTsTemplate;
  "pg_catalog.pg_type": PgCatalogPgType;
  "pg_catalog.pg_user": PgCatalogPgUser;
  "pg_catalog.pg_user_mapping": PgCatalogPgUserMapping;
  "pg_catalog.pg_user_mappings": PgCatalogPgUserMappings;
  "pg_catalog.pg_views": PgCatalogPgViews;
}
