#!/bin/bash
mkdir -p /opt/whdata/loadreports

while true; do
  LOGDIR=/opt/whdata/loadreports/$(date +%Y%m%d)
  mkdir -p $LOGDIR
  LOGFILE=$LOGDIR/$(date +%H%M%S)

  date > $LOGFILE
  /opt/wh/whtree/bin/wh db transactions >> $LOGFILE 2>&1
  [ -n "$WEBHARE_DBASENAME" ] && /opt/wh/whtree/bin/wh db locks >> $LOGFILE 2>&1
  /opt/wh/whtree/bin/wh db transactions --allinfo >> $LOGFILE 2>&1
  ps faux >> $LOGFILE 2>&1
  [ -n "$WEBHARE_DBASENAME" ] && /opt/wh/whtree/bin/wh psql -c "select * from pg_locks" >> $LOGFILE 2>&1

  SLEEPINTERVAL=$(cat /opt/whdata/loadreports/interval 2>/dev/null)
  if [ -z "$SLEEPINTERVAL" ]; then
    SLEEPINTERVAL=300 # once every 5 minutes
  fi

  sleep $SLEEPINTERVAL
done
