import type { LogLevel } from "esbuild";

/** Last compilation state. Generated by any compiletask (even offline!) but only read by assetpack control. */
export interface AssetPackState {
  bundleTag: string;
  fileDependencies: string[];
  missingDependencies: string[];
  start: Date;

  //TODO get rid of topError, its appears to be filled inconsistently
  topError: string;
  errors: Array<{
    message: string;
    resource: string;
    line: number;
    col: number;
    length: number;
  }>;

  //we include this to help debug unexpected recompiles
  lastCompileSettings: RecompileSettings;
}

/** Structure of the manifest.json file */
export interface AssetPackManifest {
  version: number;
  assets: Array<{
    subpath: string;
    compressed: boolean;
    sourcemap: boolean;
  }>;
}

/** HareScript compatible BundleConfig. Obsolete, we don't really have to share this with HS anymore */
export interface BundleConfig {
  languages: string[];
  whpolyfills: boolean;
  compatibility: string;
  environment: string;
  //TODO replace with a true plugin invocation/hook where the callee gets to update the settings
  esbuildsettings: string;
  extrarequires: string[];
  basecompiletoken: string;
}

/** HareScript compatible Bundle settings. Obsolete, we don't really have to share this with HS anymore */
export interface Bundle {
  bundleconfig: BundleConfig;
  entrypoint: string;
  outputpath: string;
  isdev: boolean;
  outputtag: string;
}

/** Recompile request. Include full bundle configuration for compatibility with adhoc compilations (as we'd otherwise just get it from extracted assetpack config) */
export interface RecompileSettings {
  logLevel?: LogLevel;
  bundle: Bundle;
}
