import type { LogLevel } from "esbuild";
import type { ValidationMessageWithType } from "../devsupport/validation";
import type { AssetPack } from "@mod-system/js/internal/generation/gen_extracts";

/** Last compilation state. Generated by any compiletask (even offline!) but only read by assetpack control. */
export interface AssetPackState {
  bundleTag: string;
  fileDependencies: string[];
  missingDependencies: string[];
  start: Date;

  messages: ValidationMessageWithType[];

  //we include this to help debug unexpected recompiles
  lastCompileSettings: RecompileSettings;
}

/** Structure of the manifest.json file */
export interface AssetPackManifest {
  version: number;
  start: string;
  assets: Array<{
    subpath: string;
    compressed: boolean;
    sourcemap: boolean;
    sha384?: string; //pre-5.8 WHs may not have sha384 and for subresource/skipping we don't need to calculate these for compressed files
  }>;
}

/** HareScript compatible Bundle settings. Obsolete, we don't really have to share this with HS anymore */
export interface Bundle {
  config: AssetPack;
  outputpath: string;
  isdev: boolean;
}

/** Recompile request. Include full bundle configuration for compatibility with adhoc compilations (as we'd otherwise just get it from extracted assetpack config) */
export interface RecompileSettings {
  logLevel?: LogLevel;
  bundle: Bundle;
}
