# shellcheck shell=bash
# We can't mark this script as executable as it shouldn't be run on a build host

# Updated 2019-10-02 (update this timestamp if nothing else to pull in new dependencies)

# Set up the image - the inital 'base' step that pulls in all the rarely changing Ubuntu packages

# Build up a clean OS addition layer
# Remove the waiting time generated by the embedded SSH key.
# For easier debugging: strace telnet iproute lsof tcpdump
# For envsubst: gettext-base
# Packages not needed for building: curl strace wget
# TODO - createrepo can go if we don't need WH1 to build repositories anymore
# stunnel: some modules use it for connectivity. must be a stunnel version with PSK support
# liberation-fonts: fonts that look like Arial, Times New Roman, Courier New

# Fail on any error
set -eo pipefail
PACKAGES=()

# Keep dnf downloads
grep -q '^keepcache' /etc/dnf/dnf.conf && \
  ( sed -i 's/^keepcache=.*/keepcache=1/' /etc/dnf/dnf.conf || \
    sed -i '/^\[main\]/a keepcache=1' /etc/dnf/dnf.conf )

# Drop in dirs used by the build
mkdir -p /opt/wh/whtree/etc/startup.d /opt/whdata/installedmodules/

# Setup users
## Group for WebHare's data directory. Not fully used yet, but keeps chrome out of it
groupadd --gid 20000 whdata
## User and group for Chrome. We really want to keep a browser far away from our data
groupadd --gid 20001 chrome

## And the uses
useradd --create-home --uid 20001 --gid 20001 --shell /bin/false chrome
useradd --uid 20002 --user-group --groups whdata opensearch
useradd --uid 20003 --user-group --groups whdata postgres

# Enable epel
dnf install -y epel-release

# Allow using a nightly build of node, eg:
# WEBHARE_NODE_MAJOR=23 WHBUILD_NODE_URL=https://nodejs.org/download/nightly/v23.0.0-nightly202408194f94397650/node-v23.0.0-nightly202408194f94397650-linux-arm64.tar.xz wh buildcontainer
if [ -n "$WHBUILD_NODE_URL" ]; then
  pushd /opt
  curl --fail "$WHBUILD_NODE_URL" | tar Jx
  ln -s /opt/node-*/bin/* /usr/local/bin/
  popd
else
  # Alma currently ships 22.x and we expect RL to always be a bit behind, only picking up LTS releases
  curl -fsSL https://rpm.nodesource.com/setup_24.x | bash -
  PACKAGES+=(nodejs)
fi

# Modify root to live in /opt/whdata/root/ so data there is preserved between restarts
# usermod -d /opt/whdata/root root - doesn't work:  'usermod: user root is currently used by process 1'
sed -e 's/:\/root:/:\/opt\/whdata\/root:/' /etc/passwd > /etc/passwd.new && mv /etc/passwd.new /etc/passwd

# 2025-06-19: Add 'socat' because a lot of quick debugging connections depend on a forwarder
# 2025-05-16: Converted from Ubuntu to RL 10 dependencies. Note that openjdk pulls in the most dependencies but both opensearch and pdfkit require it
#             seeing if we can use java-21-openjdk-headless without breaking pdftk?

# 2023-04-02: Added 'libaio1' - it's a dependency for oracle instantclient
# 2021-12-22: Added 'zip' for finalize-webhare (building history/source.zips)
# 2022-08-05: Added 'jq' to parse webhare.version. But keep it for analyzing logs!
# 2023-08-23: Restore openssh-server, our test_sftp needs it (and sftp needs a ssh client)

PACKAGES+=(
 busybox # Needed for runsvdir
 certbot #EPEL
 fontconfig
 freetype
 gettext
 giflib
 git
 inotify-tools #EPEL
 jq
 java-21-openjdk-headless
 liberation-fonts
 less
 libaio
 lftp
 libmaxminddb
 libicu
 libjpeg-turbo
 libpng
 libtiff
 openssl
 pixman
 procps-ng
 psmisc
 rsync
 socat
 stunnel
 tar
 unzip
 valgrind
 vim
 zip
)

# Chrome deps
PACKAGES+=(
  atk
  at-spi2-atk
  libxcb
  libxkbcommon
  libX11
  libXcomposite
  libXdamage
  libXext
  libXfixes
  libXrandr
  libgbm
  pango
)

dnf install -y "${PACKAGES[@]}"

source "${BASH_SOURCE%/*}/setup-base-shared.sh"


# downgrade node if we meet a broken version
# 24.10.x ships with broken npm 11.6.1 not installing dependencies properly, missing ajv/dist/core - https://gitlab.webhare.com/webharebv/codekloppers/-/issues/1183

# keeping downgrade code for reference
#if [[ $(node -v) =~ ^v24.10. ]]; then
# apt-get install -y --allow-downgrades nodejs=24.9.0-1nodesource1
#fi

# upgrade broken NPMs. 11.6.1 shipped with nodejs 24.10.x
if [[ "$(npm -v)" =~ ^11.6.[12]$ ]]; then
  echo "Upgrading NPM to 11.6.3 (npm -g i npm@11.6.3)"
  npm -g i npm@11.6.3
fi

if [[ $(node -v) =~ ^v22\.[0-7]\. ]] || [[ $(node -v) =~ ^v2[0-1]\. ]] ; then
  echo "$(node -v) is broken, ensure you pick up a newer version" 1>&2
  exit 1
fi

# Remove /etc/java-8-openjdk/accessibility.properties to fix PDFBOX. see https://askubuntu.com/questions/695560/assistive-technology-not-found-error-while-building-aprof-plot
# rm /etc/java-21-openjdk/accessibility.properties

ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

mkdir -p /opt/wh/whtree /opt/whdata /opt/whmodules /opt/wh/whtree/currentinstall/compilecache

# setup busyboxs' version of runsv
ln -s /usr/sbin/busybox /usr/sbin/sv
ln -s /usr/sbin/busybox /usr/sbin/runsv
ln -s /usr/sbin/busybox /usr/sbin/runsvdir

# TODO - remove certbot as soon as we have fully integrated it and WH1 no longer needs to host it
if ! certbot --version; then
  echo "Certbot failed!"
  exit 1
fi

if ! pstree ; then
  echo "Missing pstree"
  exit 1
fi
