# We can't mark this script as executable as it shouldn't be run on a build host

# Updated 2019-10-02 (update this timestamp if nothing else to pull in new dependencies)

# Set up the image - the inital 'base' step that pulls in all the rarely changing Ubuntu packages

# Build up a clean OS addition layer
# Remove the waiting time generated by the embedded SSH key.
# For easier debugging: strace telnet iproute lsof tcpdump
# For envsubst: gettext-base
# Packages not needed for building: curl strace wget
# TODO - createrepo can go if we don't need WH1 to build repositories anymore
# stunnel: some modules use it for connectivity. must be a stunnel version with PSK support
# liberation-fonts: fonts that look like Arial, Times New Roman, Courier New

# Fail on any error
set -eo pipefail

# 2023-05-30: Removed libxml2 but adding automake,autoconf,libtool to build it from source

# We don't ship the builder image to WebHare prod or CI, so there's no need to keep it small
PACKAGES="automake
    autoconf
    ccache
    libfreetype6-dev
    g++
    libgif-dev
    git
    inotify-tools
    libtool
    libaio1
    libcurl4-openssl-dev
    libmaxminddb-dev
    libicu-dev
    libjpeg-turbo8
    libjpeg-turbo8-dev
    libpng-dev
    libpq-dev
    libssl-dev
    libtiff-dev
    make
    libpixman-1-dev
    pkg-config
    python
    rapidjson-dev
"

if ! ( apt-get -q update && apt-get -qy install --no-install-recommends $PACKAGES ); then
  echo "APT-GET failed"
  exit 1
fi

# ubuntu 20.04 ships with outdated automake, libxml2 doesn't like it. download a better one
cd /tmp
curl http://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.gz | tar zxf -
cd automake-1.16.5/
./configure
make -j install

# update make too
cd /tmp
curl  https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz | tar zx
cd make-4.4.1
./configure
make install

#install emscripten. for releases see https://github.com/emscripten-core/emscripten/tags
cd /opt
git clone https://github.com/emscripten-core/emsdk.git
cd /opt/emsdk

EMSDKVERSION=3.1.59

./emsdk install "$EMSDKVERSION"
./emsdk activate "$EMSDKVERSION"
