# We can't mark this script as executable as it shouldn't be run on a build host

# Updated 2019-10-02 (update this timestamp if nothing else to pull in new dependencies)

# Set up the image - the inital 'base' step that pulls in all the rarely changing Ubuntu packages

# Build up a clean OS addition layer
# Remove the waiting time generated by the embedded SSH key.
# For easier debugging: strace telnet iproute lsof tcpdump
# For envsubst: gettext-base
# Packages not needed for building: curl strace wget
# TODO - createrepo can go if we don't need WH1 to build repositories anymore
# stunnel: some modules use it for connectivity. must be a stunnel version with PSK support
# liberation-fonts: fonts that look like Arial, Times New Roman, Courier New

# Fail on any error
set -eo pipefail

# ASSETROOT="$1"

if [ -z "$WHBUILD_DOWNLOADCACHE" ]; then
  echo WHBUILD_DOWNLOADCACHE not set
  exit 1
fi

# Keep dnf downloads
grep -q '^keepcache' /etc/dnf/dnf.conf && \
  ( sed -i 's/^keepcache=.*/keepcache=1/' /etc/dnf/dnf.conf || \
    sed -i '/^\[main\]/a keepcache=1' /etc/dnf/dnf.conf )


dnf config-manager --set-enabled crb # Needed for giflib-devel and libmaxminddb-devel

# 2025-03-16: Conversion to RL10
# 2023-05-30: Removed libxml2 but adding automake,autoconf,libtool to build it from source

# We don't ship the builder image to WebHare prod or CI, so there's no need to keep it small
PACKAGES=(
  automake
  autoconf
  ccache
  freetype-devel
  gcc-c++
  giflib-devel
  git
  inotify-tools
  libtool
  libaio
  libcurl-devel
  libmaxminddb-devel
  libicu-devel
  libjpeg-turbo
  libjpeg-turbo-devel
  libpng-devel
  postgresql-devel
  openssl-devel
  libtiff-devel
  make
  mawk # needed by libxml2
  pixman-devel
  pkgconfig
  python3
  rapidjson-devel
  valgrind-devel
)

dnf install -y "${PACKAGES[@]}"

if [ -z "$WHBUILD_EMSCRIPTEN_VERSION" ]; then
  echo "WHBUILD_EMSCRIPTEN_VERSION not set"
  exit 1;
fi

/opt/wh/vendor/emsdk/emsdk install "$WHBUILD_EMSCRIPTEN_VERSION"
/opt/wh/vendor/emsdk/emsdk activate "$WHBUILD_EMSCRIPTEN_VERSION"
echo "$WHBUILD_EMSCRIPTEN_VERSION" > /opt/wh/vendor/wh-current-emscripten-version
