#!/bin/bash

set -eo pipefail

SCRIPTPATH="$(realpath "${BASH_SOURCE[0]}")"
WEBHARE_CHECKEDOUT_TO="$(cd "${BASH_SOURCE%/*}/.."; pwd)"
source "$WEBHARE_CHECKEDOUT_TO/whtree/lib/make-functions.sh"
estimate_buildj

if [ "$WEBHARE_PLATFORM" == "linux" ]; then
  MAKE=/usr/local/bin/make #ensure we get make 4.4.1
  read -r _ TOTALMEM _ <<< "$(cat /proc/meminfo| grep ^MemTotal)"
  EXPECTMEMORY=3900000 #almost 4GB but give some tolerance
  # With too little memory the buildtoolchains will randomly segfault, and defaults for Docker/podman can be smaller than that. use eg podman machine set -m 4096
  [ "$TOTALMEM" -lt "$EXPECTMEMORY" ] && die "You need at least 4GB of memory to build WebHare ($TOTALMEM < $EXPECTMEMORY)"
else
  MAKE=gmake
fi

setup_builddir

export WEBHARE_BUILDDIR
export WHBUILD_DOWNLOADCACHE
export WHBUILD_BUILDROOT

if [ -n "$WEBHARE_IN_DOCKER" ] && [ -z "$WHBUILD_ALLOW" ]; then
  # Prevent you from accidentally breaking a running WebHare installation - did you think you were running this locally?
  die "If WEBHARE_IN_DOCKER is set you must set WHBUILD_ALLOW to be able to 'wh make'"
fi

# Is emsdk installed?
if [ -z "$WEBHARE_IN_DOCKER" ]; then
  [ -x "$WEBHARE_CHECKEDOUT_TO/vendor/emsdk/emsdk" ] || git -C "$WEBHARE_CHECKEDOUT_TO" submodule update --init --recursive
  [ -x "$WEBHARE_CHECKEDOUT_TO/vendor/emsdk/emsdk" ] || die "Submodule vendor/emsdk not present"
  # TODO skip if already activated. need to support version checks then
  # TODO can we ensure wasm-clean is invoked (ideally set a proper dep) whenever emsdk is updated?
  "$WEBHARE_CHECKEDOUT_TO/vendor/emsdk/emsdk" install 3.1.60
  "$WEBHARE_CHECKEDOUT_TO/vendor/emsdk/emsdk" activate 3.1.60
  source "$WEBHARE_CHECKEDOUT_TO/vendor/emsdk/emsdk_env.sh"
fi

# Update/regenerate platformconf.h
getwebhareversion

# Convert version number to 5 digit style used in C++/HareScript (GetWebHareVersionNumber)
if [[ $WEBHARE_VERSION =~ ^([0-9]{1})\.([0-9]{1,2})\.([0-9]{1,2})$ ]]; then
  VERSIONMAJOR="${BASH_REMATCH[1]}"
  VERSIONMINOR="${BASH_REMATCH[2]}"
  VERSIONPATCH="${BASH_REMATCH[3]}"
  [ ${#VERSIONMINOR} = 2 ] || VERSIONMINOR="0${VERSIONMINOR}"
  [ ${#VERSIONPATCH} = 2 ] || VERSIONPATCH="0${VERSIONPATCH}"
else
  die "Could not parse version number $WEBHARE_VERSION"
fi

# Generate the actual header
PLATFORMCONFHEADER="$WEBHARE_CHECKEDOUT_TO/blex/platformconf.h"
cat << HERE >> "$PLATFORMCONFHEADER".new
/* This file is generated by make.sh (wh make) */

#ifndef blex_platformconf
#define blex_platformconf

#define BLEX_BRANDING_PRODUCT_VERSION_NUMBER    ${VERSIONMAJOR}${VERSIONMINOR}${VERSIONPATCH}

#endif
HERE

# Do not overwrite if no changes!
if ! diff -q "$PLATFORMCONFHEADER".new "$PLATFORMCONFHEADER"; then
  echo "Updating $PLATFORMCONFHEADER"
  mv "$PLATFORMCONFHEADER".new "$PLATFORMCONFHEADER"
else
  rm "$PLATFORMCONFHEADER".new
fi

export WHBUILD_CCACHE_DIR="$WHBUILD_BUILDROOT/ccache" #for ccache only
export WHBUILD_BUILDCACHE_DIR="$WHBUILD_BUILDROOT/buildcache" #for other build artifcates

mkdir -p "$WHBUILD_CCACHE_DIR" "$WHBUILD_BUILDCACHE_DIR"

cd "$WEBHARE_BUILDDIR"

# Colors are nice
export GCC_COLORS=1

export SRCDIR="$WEBHARE_CHECKEDOUT_TO"
export WEBHARE_PLATFORM

retval=0
"$MAKE" -rj$WHBUILD_NUMPROC -f $WEBHARE_CHECKEDOUT_TO/builder/base_makefile "$@" || retval=$?

if [ "$retval" != "0" ]; then
  echo ""
  echo "Make failed with errorcode $retval"
  echo ""

  [ -z "$WEBHARE_IN_DOCKER" ] && cat $WEBHARE_CHECKEDOUT_TO/builder/support/failhare.txt
  exit $retval
fi

exit 0
