---
openapi: 3.1.0
info:
  title: WebHare API
  version: 0.9.0 # TODO once we're official decide whether this will follow WebHare numbering or be independent

x-webhare-authorization: "meta.ts#verifyUser"

paths:
  "/meta":
    get:
      responses:
        "200":
          description: Describes the connected user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meta"
        "401":
          $ref: "#/components/responses/unauthorized"
      x-webhare-implementation: "meta.ts#getMeta"

  "/whfs/object":
    get:
      parameters:
        - $ref: "#/components/parameters/path"
        - in: query
          name: children
          schema:
            type: boolean
            description: If set and the object is a folder, include the children objects in the response
        - in: query
          name: instances
          schema:
            type: string
            description: Set to '*' to get all instances of the object (if any)
      responses:
        "200":
          description: Returns the basic name and type info for any WHFS object and the children for WHFS folders
          content:
            application/json:
              schema:
                type: object
                unevaluatedProperties: false
                allOf:
                  - $ref: "#/components/schemas/RetrievedWHFSObject"
                  - type: object
                    properties:
                      children:
                        type: array
                        description: Child objects in a folder.
                        items:
                          $ref: "#/components/schemas/RetrievedWHFSObject"
                      instances:
                        $ref: "#/components/schemas/RetrievedWHFSInstances"

        "403":
          $ref: "#/components/responses/forbidden"
        "404":
          $ref: "#/components/responses/notfound"
      x-webhare-implementation: "whfs.ts#getWHFSObject"

    post:
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        description: The WHFS object to create
        required: true
        content:
          application/json:
            schema:
              type: object
              unevaluatedProperties: false
              allOf:
                - $ref: "#/components/schemas/CreateWHFSObject"
                - type: object
                  properties:
                    instances:
                      $ref: "#/components/schemas/WHFSInstances"
      responses:
        "201":
          description: Creation succesful
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
      x-webhare-implementation: "whfs.ts#createWHFSObject"

    patch:
      parameters:
        - $ref: "#/components/parameters/path"
      requestBody:
        description: The WHFS object metadata to update
        required: true
        content:
          application/json:
            schema:
              type: object
              unevaluatedProperties: false
              allOf:
                - $ref: "#/components/schemas/WHFSObject"
                - type: object
                  properties:
                    instances:
                      $ref: "#/components/schemas/WHFSInstances"
      responses:
        "200":
          description: Update successful
        "403":
          $ref: "#/components/responses/forbidden"
        "404":
          $ref: "#/components/responses/notfound"
      x-webhare-implementation: "whfs.ts#updateWHFSObject"

  "/wrd":
    get:
      responses:
        "200":
          description: Returns the WRD schemas available to the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WRDSchema"
        "400":
          $ref: "#/components/responses/badrequest"
        "401":
          $ref: "#/components/responses/unauthorized"
      x-webhare-implementation: "wrd.ts#getSchemas"

  "/wrd/{schema}/type":
    get:
      description: List the WRD types in a schema
      parameters:
        - $ref: "#/components/parameters/xschema"
      responses:
        "200":
          description: The types
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Types"
      x-webhare-implementation: "wrd.ts#listTypes"

  # we are reservering /wrd/{schema} for the actual schema metadata but we don't have a YAML/JSON structure yet
  # we are reservering /wrd/{schema}/query for joining queries
  "/wrd/{schema}/type/{type}/query":
    post:
      description: Query call
      parameters:
        - $ref: "#/components/parameters/xschema"
        - $ref: "#/components/parameters/type"
      requestBody:
        description: The query
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TypeQuery"

      responses:
        "200":
          description: The query result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TypeQueryResult"
        "401":
          $ref: "#/components/responses/unauthorized"
      x-webhare-implementation: "wrd.ts#queryType"

  "/wrd/{schema}/type/{type}/entity":
    post:
      # TODO we could offer an importMode parameter OR an import endpoint. but do we even want external users to use importMode? eg sync won't require it as its a pull interface and using Temp entities may be safer anyway
      description: Create a new WRD entity
      parameters:
        - $ref: "#/components/parameters/xschema"
        - $ref: "#/components/parameters/type"
      requestBody:
        description: The entity data to import
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEntityBody"

      responses:
        "201":
          description: The created entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEntityResult"
      x-webhare-implementation: "wrd.ts#createEntity"

  "/wrd/{schema}/type/{type}/entity/{entity}":
    patch:
      # TODO we could offer an importMode parameter OR an import endpoint. but do we even want external users to use importMode? eg sync won't require it as its a pull interface and using Temp entities may be safer anyway
      description: Update an entity
      parameters:
        - $ref: "#/components/parameters/xschema"
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/entity"
      requestBody:
        description: The entity data to import
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEntityBody"

      responses:
        "204":
          description: The entity is updated
      x-webhare-implementation: "wrd.ts#updateEntity"

  "/wrd/{schema}/type/{type}/entity/{entity}/apitoken":
    get:
      description: List API tokens owned by the entity
      parameters:
        - $ref: "#/components/parameters/xschema"
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/entity"
      responses:
        "200":
          description: The list of API tokens
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiToken"
        "404":
          description: The entity is not found
      x-webhare-implementation: "wrd.ts#listApiTokens"

    post:
      description: Create a new API token for the entity
      parameters:
        - $ref: "#/components/parameters/xschema"
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/entity"
      requestBody:
        description: The API token data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateApiTokenBody"

      responses:
        "201":
          description: The created API token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedApiToken"
        "404":
          description: The entity is not found
      x-webhare-implementation: "wrd.ts#createApiToken"

components:
  parameters:
    xschema: # Prefixed with 'x' otherwise openapi-typescript doesn't pick it up
      in: path
      name: schema
      required: true
      schema:
        type: string
        description: WRD schema name (generally `module:schema` with `:` encoded as `%3A` in the final URL)

    type:
      in: path
      name: type
      required: true
      schema:
        type: string
        description: WRD type name, camel-cased

    entity:
      in: path
      name: entity
      required: true
      schema:
        type: string
        description: wrdGuid of the affected entity (UUID format)
        format: uuid

    path:
      in: query
      name: path
      required: false
      schema:
        type: string
        description: The WHFS path to an object (defaults to root folder if not provided)

  schemas:
    ## Global types
    defaulterror: # This schema must be declared to use TypedRestRequest.createErrorResponse in TypeScript
      type: object
      properties:
        error:
          type: string
        status:
          type: number

    Meta:
      type: object
      additionalProperties: false
      properties:
        user:
          $ref: "#/components/schemas/User"

    User:
      type: object
      additionalProperties: false
      properties:
        guid:
          type: string
          description: User's unique identifier
          format: uuid
        email:
          type: string
          description: The email address of the user

    ## WHFS API
    WHFSObject:
      type: object
      properties:
        name:
          type: string
          description: The name of the WHFS object
        type:
          type: string
          description: The WHFS type (scoped type)
        whfsPath:
          type: string
          description: Full WHFS path of the object
        isFolder:
          type: boolean
          description: If true, this object is a folder
        modified:
          type: string
          format: date-time
          description: The last modification date/time of the object
        # We ignore updates to readonly properties so you can reasonably easy pass the output of GET back into POST.
        link:
          type: string
          description: The link to the object if published. Ignored if set

    CreateWHFSObject:
      $ref: "#/components/schemas/WHFSObject"
      required: [name, type]

    RetrievedWHFSObject:
      $ref: "#/components/schemas/WHFSObject"
      required: [name, type, whfsPath, modified]

    WHFSInstance:
      type: object
      required: [whfsType, data]
      properties:
        whfsType:
          type: string
          description: The WHFS instance type (scoped type)
        clone:
          type: string
          description: The clone identifier if applicable. Ignored when setting
          enum:
            - onCopy
            - onArchive
            - never
        data:
          type: object
          description: The metadata content of the WHFS instance
          additionalProperties: true

    RetrievedWHFSInstance:
      $ref: "#/components/schemas/WHFSInstance"
      required: [whfsType, data, clone]

    RetrievedWHFSInstances:
      type: array
      description: List of instances to get/set
      items:
        $ref: "#/components/schemas/RetrievedWHFSInstance"

    WHFSInstances:
      type: array
      description: List of instances to get/set
      items:
        $ref: "#/components/schemas/WHFSInstance"

    ## WRD API
    MetaType:
      type: string
      enum: [object, attachment, link, domain]

    WRDSchema:
      type: object
      additionalProperties: false
      required: [tag]
      properties:
        tag:
          type: string
          description: The name of the WRD schema

    CreateEntityBody:
      type: object
      additionalProperties: false
      required: [fields]
      properties: # NOTE wrap the fields so we have room for other import parameters, eg 'temp' or something like ifnew/entitykey for upsert like actions
        fields:
          $ref: "#/components/schemas/EntityFields"

    UpdateEntityBody:
      type: object
      additionalProperties: false
      required: [fields]
      properties: # NOTE wrap the fields so we have room for other import parameters, eg de-temp. historymode?
        fields:
          $ref: "#/components/schemas/EntityFields"

    EntityFields:
      type: object
      additionalProperties: true
      properties:
        wrdGuid:
          type: string
          description: The entity's guid
          format: uuid
        wrdTag:
          type: string
          description: The entity's tag
          pattern: "^[A-Z][A-Z0-9_]{1,63}$"

    CreateEntityResult:
      type: object
      additionalProperties: false
      properties:
        wrdGuid:
          type: string
          description: The new entity's guid
          format: uuid

    Type:
      type: object
      additionalProperties: false
      required: [metaType]
      properties:
        metaType:
          $ref: "#/components/schemas/MetaType"

    Types:
      type: object
      #patternProperties: # "^[a-z][A-Z0-9_]{0,63}$": # the type's camelcased tag TODO not supported by openapi=typescript but see https://github.com/openapi-ts/openapi-typescript/pull/2288/files
      additionalProperties: # the type's camelcased tag
        $ref: "#/components/schemas/Type"

    TypeQuery:
      type: object
      additionalProperties: false
      properties:
        filters:
          type: array
          items:
            type: object
            additionalProperties: false
            required:
              - field
              - matchType
              - value
            properties:
              field:
                type: string
                description: The field to filter on
              matchType:
                type: string
                description: The match type (e.g., '=', '!=', '>', '<', etc.)
              value:
                type: string
                description: The value to match against the field
        fields:
          type: array
          items:
            type: string

    TypeQueryResult:
      type: object
      additionalProperties: false
      required: [results]
      properties:
        results:
          type: array
        nextToken:
          type: string
          nullable: true
          description: A token for pagination, if applicable

    CreateApiTokenBody:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
          description: A title for the API token
          maxLength: 256
        scopes:
          type: array
          items:
            type: string
          description: The scopes for the API token
        expires:
          type: string
          format: date-time
          nullable: true

    ApiToken:
      type: object
      required: [created]
      properties:
        created:
          type: string
          format: date-time
          nullable: true
        expires:
          type: string
          format: date-time
        title:
          type: string

    CreatedApiToken: # ApiToken extended with the actual token
      type: object
      allOf:
        - "$ref": "#/components/schemas/ApiToken"
        - type: object
          required: [token]
          properties:
            token:
              type: string
              description: The created API token
      unevaluatedProperties: false

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    badrequest:
      description: Invalid request
    unauthorized:
      description: Authorization bearer token is missing or invalid
    notfound:
      description: The requested resource was not found
    forbidden:
      description: Access to the requested resource is forbidden

security:
  - bearerAuth: [] # use the same name as above
