import { loadlib } from "@webhare/harescript";
import * as bcrypt from "bcrypt";

/* We use bcrypt so we won't have to fire up WASM for HS's implementation. bcrypt is strong and safe enough for our purposes but has two drawbacks:
   - only the first 72 bytes of the password are hashed, so longer passwords will be truncated
   - it's not officically recommended so may introduce complexities to audits

  OWASP recommends argon2id (see https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html), so as soon as we don't need HareScript
  to verify our passwords (it may not be worth it to integrate argon2id in HS) we should consider switching over and use isPasswordStillSecure to phase out bcrypt hashes

  https://www.npmjs.com/package/bcrypt:
  - bcrypt supports $2a$ and $2b$ prefix bcrypt hashes. $2x$ and $2y$ hashes are specific to bcrypt implementation developed for John the Ripper. In theory, they should be compatible with $2b$ prefix.
  - Compatibility with hashes generated by other languages is not 100% guaranteed due to difference in character encodings. However, it should not be an issue for most cases.

  As we always used UTF8 we should be fully compatible
*/

const expectRounds = 10;

export function isPasswordStillSecure(hash: string): boolean {
  if (!hash.startsWith("WHBF:$2y$"))
    return false;

  const rounds = parseInt(hash.split("$")[2], 10);
  return rounds >= expectRounds;
}

export async function verifyWebHarePasswordHash(password: string, hash: string): Promise<boolean> {
  if (hash.startsWith("PLAIN:"))
    return password === hash.substring(6);

  if (hash.startsWith("WHBF:$2y$")) //WebHare uses a $2y$ prefix but bcrypt expects $2b$
    return await bcrypt.compare(password, "$2b$" + hash.substring(9));

  return await loadlib("wh::crypto.whlib").VERIFYWEBHAREPASSWORDHASH(password, hash);
}

export async function createWebHarePasswordHash(password: string): Promise<string> {
  //convert bcrypt's hash (starts with $2b$) to WebHare's format (starts with $2y$)
  return "WHBF:$2y$" + (await bcrypt.hash(password, expectRounds)).substring(4);
}
